### ISSUE TITLE
Should not be using `babel-node` for "production" use

### ISSUE THREAD

**Issue by track0x1** [lmammino/judo-heroes-2#10]
I just came across this repo looking for universal React app examples and noticed your "production" mode server is using `babel-node` which says in the docs is not meant for production use.
Maybe just switch to babelifying the server code and running that in regular node?
https://babeljs.io/docs/usage/cli/#babel-node

**Comment by lmammino** [comment]
Hello @track0x1, yours is definitely a good point.

Since this was a tutorial (and not really intended to be run as a "business-oriented" production website) I didn't want to over-complicate the setup and leave things as simple as possible. It's also true that beginners might think that it's a good idea to run babel-node in production, so I'll try to address the issue soon.

thanks for your comment! ;)

**Comment by lmammino** [comment]
Addressed in 09bc8b4

**Comment by lmammino** [comment]
Reopened after this comment https://github.com/lmammino/judo-heroes-2/commit/09bc8b45d3e798a379f6b1a26265c96ab6662608#commitcomment-22764182

**Comment by lmammino** [comment]
Re-addressed and Re-closing! Thanks for the support @track0x1
