### ISSUE TITLE
Explain build and run script decisions?

### ISSUE THREAD

**Issue by ghost** [lmammino/judo-heroes-2#3]
Hi Luciano!

Could you elaborate on why you choose what you did for the build and run scripts?

  "scripts": {
    "start": "npm run build && babel-node src/server.js",
    "start:dev": "export NODE_ENV=development && npm run build:dev && nodemon --exec babel-node -- src/server.js",
    "start:universal": "export UNIVERSAL=true && npm run start",
    "start:dev:universal": "export NODE_ENV=development && export UNIVERSAL=true && npm run start:dev",
    "build": "NODE_ENV=production webpack -p",
    "build:dev": "webpack -d",
    "build:dev:watch": "webpack -d --watch"
  }

In particular, why did you drop HMR / webpack dev server in judo-heroes-2 versus judo-heroes?

Thanks,
Anthony

**Comment by ghost** [comment]
Also wanted to add, why not use webpack with a babel loader so you don't need babel node?

**Comment by lmammino** [comment]
Hello @McFlurriez,
sorry for the late reply.

Regarding your first question, there's really no strong reason. I didn't really needed to have that in palce since the app was already designed and I just didn't want to spend the time to see how to configure HMR with Webpack2.

Regarding your second question, in general I do what you suggested (not to use babel node in production), but for the sake of this example I didn't want to add the extra complexity of providing a webpack setup also for the server part.

Let me know if you have more questions :)

regards
