### ISSUE TITLE
WebPack Compiler with Third Party APIs like Mapbox

### ISSUE THREAD

**Issue by phoenisx** [lmammino/judo-heroes-2#9]
I have trouble using sass-loader and using third party APIs when I try to run the Node server. Though I have made some modifications in your code-base, like adding Webpack compiler and Webpack-Dev-Middleware to the Express, but during the start of Node Express Server, the Webpack -d runs fine (i.e. Build is successfull), but the Server doesn't start.

It gives me following error:

* First when Scss files are imported to React Components, I get Syntax error for `@import` in any `.scss` files.
* To handle this, I removed Sass Imports (Just to check if it works without Sass compilation), but after that, I got following error:

```javascript
mapbox-gl.js:404
"use strict";module.exports=self;
                            ^

ReferenceError: self is not defined
```

where mapbox-gl is a third-party library, and I import them in the Components, using the following plugin in webpack.conf:

```javascript
new webpack.ProvidePlugin({
    mapboxgl: 'mapbox-gl',
    turf: "@turf/turf"
  }),
```

My Webpack conf is right, as it works, when I start it with webpack-dev-server.... Problem is when I try to use the same settings for creating a Universal React App.

I know this is not an issue, but was hoping that you might help me here someway, as I have searched a lot and tried a lot of ways to make it work, but none of them came out true.

Thanks

**Comment by lmammino** [comment]
Hello @Shub1427,
sorry but without being able to look at some code this is very hard to troubleshoot even though I guess it's a matter of some wrong configuration in your webpack setup.

Also, since it seems you changed a lot of this tutorial code, I wouldn't consider this as an issue of this repo per se, so I am closing the issue. Feel free to reply here if you think that's not the case
